// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.calcexercise.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;
import com.xhb.core.response.HttpResponseData;

public class ExerciseDetailRequest extends HttpData {
	private String id = "";

	@NotNull 
	public String getId() {
		return this.id;
	}

	public void setId(@NotNull String id) {
		this.id = id;
	}
}
