// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.calcexercise.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;
import com.xhb.core.response.HttpResponseData;

public class ExerciseBrief extends HttpData {
	private String id = "";
	private String unitId = "";
	private String unitName = "";
	private long spendTime;
	private int rightCnt;
	private int totalCnt;
	private long timestamp;

	@NotNull 
	public String getId() {
		return this.id;
	}

	public void setId(@NotNull String id) {
		this.id = id;
	}

	@NotNull 
	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(@NotNull String unitId) {
		this.unitId = unitId;
	}

	@NotNull 
	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(@NotNull String unitName) {
		this.unitName = unitName;
	}

	
	public long getSpendTime() {
		return this.spendTime;
	}

	public void setSpendTime(long spendTime) {
		this.spendTime = spendTime;
	}

	
	public int getRightCnt() {
		return this.rightCnt;
	}

	public void setRightCnt(int rightCnt) {
		this.rightCnt = rightCnt;
	}

	
	public int getTotalCnt() {
		return this.totalCnt;
	}

	public void setTotalCnt(int totalCnt) {
		this.totalCnt = totalCnt;
	}

	
	public long getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}
}
