// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.calcexercise.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;

public class Image extends HttpData {
	private String original = "";
	private String preview = "";
	private String thumbnail = "";
	private int size;
	private int height;
	private int width;

	@NotNull 
	public String getOriginal() {
		return this.original;
	}

	public void setOriginal(@NotNull String original) {
		this.original = original;
	}

	@NotNull 
	public String getPreview() {
		return this.preview;
	}

	public void setPreview(@NotNull String preview) {
		this.preview = preview;
	}

	@NotNull 
	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(@NotNull String thumbnail) {
		this.thumbnail = thumbnail;
	}

	
	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	
	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	
	public int getWidth() {
		return this.width;
	}

	public void setWidth(int width) {
		this.width = width;
	}
}
