// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.calcexercise.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;

public class QuestionContent extends HttpData {
	private String id = "";
	private String questionBody = "";
	private long symbolType;
	private long type;
	private String answer = "";
	private String verticalJson = "";
	private String latex = "";
	private String renderTex = "";
	private long sourceId;

	@NotNull 
	public String getId() {
		return this.id;
	}

	public void setId(@NotNull String id) {
		this.id = id;
	}

	@NotNull 
	public String getQuestionBody() {
		return this.questionBody;
	}

	public void setQuestionBody(@NotNull String questionBody) {
		this.questionBody = questionBody;
	}

	
	public long getSymbolType() {
		return this.symbolType;
	}

	public void setSymbolType(long symbolType) {
		this.symbolType = symbolType;
	}

	
	public long getType() {
		return this.type;
	}

	public void setType(long type) {
		this.type = type;
	}

	@NotNull 
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(@NotNull String answer) {
		this.answer = answer;
	}

	@NotNull 
	public String getVerticalJson() {
		return this.verticalJson;
	}

	public void setVerticalJson(@NotNull String verticalJson) {
		this.verticalJson = verticalJson;
	}

	@NotNull 
	public String getLatex() {
		return this.latex;
	}

	public void setLatex(@NotNull String latex) {
		this.latex = latex;
	}

	@NotNull 
	public String getRenderTex() {
		return this.renderTex;
	}

	public void setRenderTex(@NotNull String renderTex) {
		this.renderTex = renderTex;
	}

	
	public long getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(long sourceId) {
		this.sourceId = sourceId;
	}
}
