// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.calcexercise.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;
import com.xhb.core.response.HttpResponseData;

public class QuestionDetail extends HttpData {
	private QuestionContent questionContent;
	private QuestionRecord questionRecord;

	@NotNull 
	public QuestionContent getQuestionContent() {
		return this.questionContent;
	}

	public void setQuestionContent(@NotNull QuestionContent questionContent) {
		this.questionContent = questionContent;
	}

	@NotNull 
	public QuestionRecord getQuestionRecord() {
		return this.questionRecord;
	}

	public void setQuestionRecord(@NotNull QuestionRecord questionRecord) {
		this.questionRecord = questionRecord;
	}
}
