// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.calcexercise.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;

public class QuestionRecord extends HttpData {
	private String questionId = "";
	private boolean correct;
	private long spendTime;
	private String answerTxt = "";
	private Image handWriting;

	@NotNull 
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(@NotNull String questionId) {
		this.questionId = questionId;
	}

	
	public boolean isCorrect() {
		return this.correct;
	}

	public void setCorrect(boolean correct) {
		this.correct = correct;
	}

	
	public long getSpendTime() {
		return this.spendTime;
	}

	public void setSpendTime(long spendTime) {
		this.spendTime = spendTime;
	}

	@NotNull 
	public String getAnswerTxt() {
		return this.answerTxt;
	}

	public void setAnswerTxt(@NotNull String answerTxt) {
		this.answerTxt = answerTxt;
	}

	@NotNull 
	public Image getHandWriting() {
		return this.handWriting;
	}

	public void setHandWriting(@NotNull Image handWriting) {
		this.handWriting = handWriting;
	}
}
