// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.calcexercise.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;
import com.xhb.core.response.HttpResponseData;

public class WrongListResponse extends HttpResponseData {
	private boolean hasMore;
	private long lastTimestamp;
	private long total;
	private java.util.ArrayList<WrongBrief> list;

	
	public boolean isHasMore() {
		return this.hasMore;
	}

	public void setHasMore(boolean hasMore) {
		this.hasMore = hasMore;
	}

	
	public long getLastTimestamp() {
		return this.lastTimestamp;
	}

	public void setLastTimestamp(long lastTimestamp) {
		this.lastTimestamp = lastTimestamp;
	}

	
	public long getTotal() {
		return this.total;
	}

	public void setTotal(long total) {
		this.total = total;
	}

	@NotNull 
	public java.util.ArrayList<WrongBrief> getList() {
		return this.list;
	}

	public void setList(@NotNull java.util.ArrayList<WrongBrief> list) {
		this.list = list;
	}
}
