// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.calcexercise.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;
import com.xhb.core.response.HttpResponseData;

public class WrongBrief extends HttpData {
	private String unitId = "";
	private String unitName = "";
	private java.util.ArrayList<QuestionContent> questions;
	private long timestamp;

	@NotNull 
	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(@NotNull String unitId) {
		this.unitId = unitId;
	}

	@NotNull 
	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(@NotNull String unitName) {
		this.unitName = unitName;
	}

	@NotNull 
	public java.util.ArrayList<QuestionContent> getQuestions() {
		return this.questions;
	}

	public void setQuestions(@NotNull java.util.ArrayList<QuestionContent> questions) {
		this.questions = questions;
	}

	
	public long getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}
}
